apiVersion: v2
name: ms-services-rest
description: This is a Helm chart for the ms-services REST service
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: ms-base
    version: 0.0.14
    repository: "https://www.codedesignplus.com/helm-charts/"