apiVersion: v2
name: ms-locations-rest
description: This is a Helm chart for the ms-locations REST service
type: application
version: 0.0.4
appVersion: "0.0.4"
dependencies:
  - name: ms-base
    version: 0.0.16
    repository: "https://www.codedesignplus.com/helm-charts/"