apiVersion: v2
name: ms-archetype-worker
description: This is a Helm chart for the ms-archetype Worker service
type: application
version: 0.0.1
appVersion: "0.0.1"
dependencies:
  - name: ms-base
    version: 0.0.1
    repository: "https://www.codedesignplus.com/helm-charts/"